// Note:
// This is for the image next to the text boxes generated by user and the bot

import React from "react";

export const UserAvatar = () => (
  <img src="/user-avatar.png" alt="User Avatar" className="avatar" />
);

export const BotAvatar = () => (
  <img src="/bot-avatar.png" alt="Bot Avatar" className="avatar" />
);
